version: '3.8'
services:
  server:
    build: ./source_code
    image: server:latest
    environment:
      - NODE_ENV=production
      # Increase Node workers per container for more concurrency (tune per host CPU)
      - CLUSTER_WORKERS=2
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
